In [1]:
import numpy as np

# Datatypes and Attributes

In [2]:
# Main Datatype is ndarrray n dimentions arrays
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
type(array1)

numpy.ndarray

In [4]:
a2=np.array([[1,2.5,3.3],
             [4,5.6,6.6]])
a3=np.array([[[1,2.5,3.3],
             [4,5.6,6.6],
            [7.7, 8, 9]],[
            [56,76,76],
            [43,32,23],
            [21,23,45]
            ]])
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [5]:
a3

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6],
        [ 7.7,  8. ,  9. ]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ],
        [21. , 23. , 45. ]]])

In [6]:
#Attributes
array1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
array1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
array1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

In [11]:
array1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
#CREATE A DATAFRAME FROM A NUMPY ARRRAY
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.5  3.3
1  4.0  5.6  6.6

# Creating Arrays

In [13]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int64')

In [15]:
ones=np.ones((2,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros=np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array=np.random.randint(0,10,size=(3,5))#3 row and 5 column
random_array

array([[9, 6, 0, 1, 8],
       [4, 4, 4, 8, 7],
       [1, 2, 2, 8, 9]])

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array.size

15

In [25]:
random_array2=np.random.rand(2,5)

In [26]:
random_array2

array([[0.08498871, 0.50106021, 0.63724189, 0.07953336, 0.85895091],
       [0.92451035, 0.11721541, 0.75716707, 0.54368795, 0.9649517 ]])

In [27]:
# P-seudo-random numbers
np.random.seed(seed=0)
random_array3=np.random.randint(10, size=(5,2))
random_array3

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4]])

# VIEWING ARRAYS AND MATRICES

In [28]:
np.unique(random_array3)

array([0, 2, 3, 4, 5, 7, 9])

In [29]:
# Indexing 
a3

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6],
        [ 7.7,  8. ,  9. ]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ],
        [21. , 23. , 45. ]]])

In [30]:
a3[:2, :2, :3]

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ]]])

In [31]:
a4=np.random.randint(5,size=(2,3,4,5))

In [32]:
a4

array([[[[0, 0, 4, 2, 1],
         [0, 1, 1, 0, 1],
         [4, 3, 0, 3, 0],
         [2, 3, 0, 1, 3]],

        [[3, 3, 0, 1, 1],
         [1, 0, 2, 4, 3],
         [3, 2, 4, 2, 0],
         [0, 4, 0, 4, 1]],

        [[4, 1, 2, 2, 0],
         [1, 1, 1, 1, 3],
         [3, 2, 3, 0, 3],
         [4, 1, 2, 4, 3]]],


       [[[4, 4, 4, 3, 4],
         [4, 4, 0, 4, 3],
         [2, 0, 1, 1, 3],
         [0, 0, 1, 2, 4]],

        [[2, 0, 3, 2, 2],
         [0, 1, 0, 2, 2],
         [3, 2, 3, 2, 1],
         [2, 3, 3, 3, 2]],

        [[3, 4, 1, 2, 3],
         [1, 2, 1, 4, 2],
         [3, 0, 3, 2, 3],
         [0, 0, 0, 3, 2]]]])

In [33]:
type(a4)

numpy.ndarray

In [34]:
a4.dtype

dtype('int64')

In [35]:
a4.ndim

4

In [36]:
a4.shape

(2, 3, 4, 5)

In [37]:
#Get First 4 Numbers of the Inner most arrays
a4[:,:,:3,:]

array([[[[0, 0, 4, 2, 1],
         [0, 1, 1, 0, 1],
         [4, 3, 0, 3, 0]],

        [[3, 3, 0, 1, 1],
         [1, 0, 2, 4, 3],
         [3, 2, 4, 2, 0]],

        [[4, 1, 2, 2, 0],
         [1, 1, 1, 1, 3],
         [3, 2, 3, 0, 3]]],


       [[[4, 4, 4, 3, 4],
         [4, 4, 0, 4, 3],
         [2, 0, 1, 1, 3]],

        [[2, 0, 3, 2, 2],
         [0, 1, 0, 2, 2],
         [3, 2, 3, 2, 1]],

        [[3, 4, 1, 2, 3],
         [1, 2, 1, 4, 2],
         [3, 0, 3, 2, 3]]]])

# Manipulating and Comparing Arrays

## Arithmetic

In [38]:
array1

array([1, 2, 3])

In [39]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [40]:
array1+ones

array([2., 3., 4.])

In [41]:
array1-ones

array([0., 1., 2.])

In [42]:
array1* ones

array([1., 2., 3.])

In [43]:
array1 / ones

array([1., 2., 3.])

In [44]:
array1%ones

array([0., 0., 0.])

In [45]:
a2/array1

array([[1.  , 1.25, 1.1 ],
       [4.  , 2.8 , 2.2 ]])

In [46]:
a2 // array1 # // for floor divsion removoes decimals

array([[1., 1., 1.],
       [4., 2., 2.]])

In [47]:
#a2 ** 2
np.square(a2)

array([[ 1.  ,  6.25, 10.89],
       [16.  , 31.36, 43.56]])

In [48]:
a2 % 2

array([[1. , 0.5, 1.3],
       [0. , 1.6, 0.6]])

In [49]:
np.exp(array1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [50]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229])

## Aggrigations

In [51]:
list=[1,2,3]
list

[1, 2, 3]

In [52]:
type(list)

list

In [53]:
sum(list)

6

In [54]:
np.sum(list) 
# Use sum() for python datatypes and np.sum for numpy arrays

6

In [55]:
array1

array([1, 2, 3])

In [56]:
# Massive Arrays
massive_arrays= np.random.random(1000)

In [57]:
massive_arrays.size

1000

In [58]:
massive_arrays[:10]

array([0.55282148, 0.16494046, 0.36980809, 0.14644176, 0.56961841,
       0.70373728, 0.28847644, 0.43328806, 0.75610669, 0.39609828])

In [59]:
%timeit sum(massive_arrays)
%timeit np.sum(massive_arrays)

68.8 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
3.45 µs ± 145 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [60]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [61]:
np.mean(a2)

3.8333333333333335

In [62]:
np.max(a2)

6.6

In [63]:
print(np.min(a2))

1.0


In [64]:
np.std(a2)

1.8660713336371206

In [65]:
np.sqrt(a2)

array([[1.        , 1.58113883, 1.81659021],
       [2.        , 2.36643191, 2.56904652]])

In [66]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [67]:
a3

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6],
        [ 7.7,  8. ,  9. ]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ],
        [21. , 23. , 45. ]]])

In [68]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [69]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2

In [ ]:
#Reshape it
a2=a2.reshape(2,3,1)

In [ ]:
a2 * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
#Reshape it .swap it..called Transpose
a2.T

# DOT & PRODUCT

In [ ]:
np.random.seed(seed=0)
mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10,size=(5,3))

In [ ]:
mat1, mat2

In [ ]:
np.dot(mat1,mat2)

In [ ]:
#Transpose mat1
mat1.T

In [ ]:
mat1.T.shape

In [ ]:
mat3=np.dot(mat1, mat2.T)

In [ ]:
mat3

# DOT PRODUCT EXAMPLE ( NUT BUTTE SALES)

In [71]:
np.random.seed(seed=0)
#Number of jars sold
sales_ammounts=np.random.randint(20, size=(5,3))
sales_ammounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [82]:
#write weekly_sales DataFrames
weekly_sales=pd.DataFrame(sales_ammounts,
                          index=["Mon","Tues","Wed","Thurs","Fri"],
                          columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [83]:
#Create prices array
prices=np.array([8,11,14])
prices

array([ 8, 11, 14])

In [84]:
prices.shape

(3,)

In [85]:
#Create Butter_Prices DataFrames
butter_prices=pd.DataFrame(prices.reshape(1,3), #reshape it its (3,) we have reshape it to (1,3)
                           index=["Price"], 
                           columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price              8             11             14

In [86]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [87]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [78]:
weekly_sales.T.shape

(3, 5)

In [90]:
daily_sales=butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  261   155  533    266  172

In [91]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [92]:
weekly_sales["Total ($)"]=daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        261
Tues               3              3              7        155
Wed                9             19             18        533
Thurs              4              6             12        266
Fri                1              6              7        172

In [93]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  261   155  533    266  172

# Comparison Operators

In [95]:
a1=array1

In [96]:
a1

array([1, 2, 3])

In [97]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [98]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [99]:
a1>=a2

array([[ True, False, False],
       [False, False, False]])

In [100]:
bool_arrays=a1>=a2

In [101]:
type(bool_arrays)

numpy.ndarray

In [102]:
bool_arrays.dtype

dtype('bool')

In [103]:
a1==a2

array([[ True, False, False],
       [False, False, False]])