In [1]:
import numpy as np

# Datatypes and Attributes

In [2]:
# Main Datatype is ndarrray n dimentions arrays
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
type(array1)

numpy.ndarray

In [4]:
a2=np.array([[1,2.5,3.3],
             [4,5.6,6.6]])
a3=np.array([[[1,2.5,3.3],
             [4,5.6,6.6],
            [7.7, 8, 9]],[
            [56,76,76],
            [43,32,23],
            [21,23,45]
            ]])
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [5]:
a3

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6],
        [ 7.7,  8. ,  9. ]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ],
        [21. , 23. , 45. ]]])

In [6]:
#Attributes
array1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
array1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
array1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

In [11]:
array1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
#CREATE A DATAFRAME FROM A NUMPY ARRRAY
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.5  3.3
1  4.0  5.6  6.6

# Creating Arrays

In [13]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int64')

In [15]:
ones=np.ones((2,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros=np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array=np.random.randint(0,10,size=(3,5))#3 row and 5 column
random_array

array([[4, 7, 2, 9, 6],
       [7, 3, 6, 8, 1],
       [8, 2, 4, 7, 8]])

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array.size

15

In [25]:
random_array2=np.random.rand(2,5)

In [26]:
random_array2

array([[0.68118126, 0.77474726, 0.68508473, 0.22687987, 0.75482558],
       [0.94882005, 0.8836473 , 0.36782868, 0.66856426, 0.357083  ]])

In [27]:
# P-seudo-random numbers
np.random.seed(seed=0)
random_array3=np.random.randint(10, size=(5,2))
random_array3

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4]])

# VIEWING ARRAYS AND MATRICES

In [28]:
np.unique(random_array3)

array([0, 2, 3, 4, 5, 7, 9])

In [29]:
# Indexing 
a3

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6],
        [ 7.7,  8. ,  9. ]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ],
        [21. , 23. , 45. ]]])

In [30]:
a3[:2, :2, :3]

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ]]])

In [31]:
a4=np.random.randint(5,size=(2,3,4,5))

In [32]:
a4

array([[[[0, 0, 4, 2, 1],
         [0, 1, 1, 0, 1],
         [4, 3, 0, 3, 0],
         [2, 3, 0, 1, 3]],

        [[3, 3, 0, 1, 1],
         [1, 0, 2, 4, 3],
         [3, 2, 4, 2, 0],
         [0, 4, 0, 4, 1]],

        [[4, 1, 2, 2, 0],
         [1, 1, 1, 1, 3],
         [3, 2, 3, 0, 3],
         [4, 1, 2, 4, 3]]],


       [[[4, 4, 4, 3, 4],
         [4, 4, 0, 4, 3],
         [2, 0, 1, 1, 3],
         [0, 0, 1, 2, 4]],

        [[2, 0, 3, 2, 2],
         [0, 1, 0, 2, 2],
         [3, 2, 3, 2, 1],
         [2, 3, 3, 3, 2]],

        [[3, 4, 1, 2, 3],
         [1, 2, 1, 4, 2],
         [3, 0, 3, 2, 3],
         [0, 0, 0, 3, 2]]]])

In [33]:
type(a4)

numpy.ndarray

In [34]:
a4.dtype

dtype('int64')

In [35]:
a4.ndim

4

In [36]:
a4.shape

(2, 3, 4, 5)

In [37]:
#Get First 4 Numbers of the Inner most arrays
a4[:,:,:3,:]

array([[[[0, 0, 4, 2, 1],
         [0, 1, 1, 0, 1],
         [4, 3, 0, 3, 0]],

        [[3, 3, 0, 1, 1],
         [1, 0, 2, 4, 3],
         [3, 2, 4, 2, 0]],

        [[4, 1, 2, 2, 0],
         [1, 1, 1, 1, 3],
         [3, 2, 3, 0, 3]]],


       [[[4, 4, 4, 3, 4],
         [4, 4, 0, 4, 3],
         [2, 0, 1, 1, 3]],

        [[2, 0, 3, 2, 2],
         [0, 1, 0, 2, 2],
         [3, 2, 3, 2, 1]],

        [[3, 4, 1, 2, 3],
         [1, 2, 1, 4, 2],
         [3, 0, 3, 2, 3]]]])

# Manipulating and Comparing Arrays

## Arithmetic

In [38]:
array1

array([1, 2, 3])

In [39]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [40]:
array1+ones

array([2., 3., 4.])

In [41]:
array1-ones

array([0., 1., 2.])

In [42]:
array1* ones

array([1., 2., 3.])

In [43]:
array1 / ones

array([1., 2., 3.])

In [44]:
array1%ones

array([0., 0., 0.])

In [45]:
a2/array1

array([[1.  , 1.25, 1.1 ],
       [4.  , 2.8 , 2.2 ]])

In [46]:
a2 // array1 # // for floor divsion removoes decimals

array([[1., 1., 1.],
       [4., 2., 2.]])

In [47]:
#a2 ** 2
np.square(a2)

array([[ 1.  ,  6.25, 10.89],
       [16.  , 31.36, 43.56]])

In [48]:
a2 % 2

array([[1. , 0.5, 1.3],
       [0. , 1.6, 0.6]])

In [49]:
np.exp(array1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [50]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229])

## Aggrigations

In [51]:
list=[1,2,3]
list

[1, 2, 3]

In [52]:
type(list)

list

In [53]:
sum(list)

6

In [54]:
np.sum(list) 
# Use sum() for python datatypes and np.sum for numpy arrays

6

In [55]:
array1

array([1, 2, 3])

In [56]:
# Massive Arrays
massive_arrays= np.random.random(1000)

In [57]:
massive_arrays.size

1000

In [58]:
massive_arrays[:10]

array([0.55282148, 0.16494046, 0.36980809, 0.14644176, 0.56961841,
       0.70373728, 0.28847644, 0.43328806, 0.75610669, 0.39609828])

In [59]:
%timeit sum(massive_arrays)
%timeit np.sum(massive_arrays)

69 µs ± 1.28 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
4.02 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [60]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [61]:
np.mean(a2)

3.8333333333333335

In [62]:
np.max(a2)

6.6

In [63]:
print(np.min(a2))

1.0


In [64]:
np.std(a2)

1.8660713336371206

In [65]:
np.sqrt(a2)

array([[1.        , 1.58113883, 1.81659021],
       [2.        , 2.36643191, 2.56904652]])

In [66]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [67]:
a3

array([[[ 1. ,  2.5,  3.3],
        [ 4. ,  5.6,  6.6],
        [ 7.7,  8. ,  9. ]],

       [[56. , 76. , 76. ],
        [43. , 32. , 23. ],
        [21. , 23. , 45. ]]])

In [68]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [69]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2

In [ ]:
#Reshape it
a2=a2.reshape(2,3,1)

In [ ]:
a2 * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
#Reshape it .swap it..called Transpose
a2.T

# DOT & PRODUCT

In [ ]:
np.random.seed(seed=0)
mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10,size=(5,3))

In [ ]:
mat1, mat2

In [ ]:
np.dot(mat1,mat2)

In [ ]:
#Transpose mat1
mat1.T

In [ ]:
mat1.T.shape

In [ ]:
mat3=np.dot(mat1, mat2.T)

In [ ]:
mat3

# DOT PRODUCT EXAMPLE ( NUT BUTTE SALES)

In [ ]:
np.random.seed(seed=0)
#Number of jars sold
sales_ammounts=np.random.randint(20, size=(5,3))
sales_ammounts

In [ ]:
#write weekly_sales DataFrames
weekly_sales=pd.DataFrame(sales_ammounts,
                          index=["Mon","Tues","Wed","Thurs","Fri"],
                          columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

In [ ]:
#Create prices array
prices=np.array([8,11,14])
prices

In [ ]:
prices.shape

In [ ]:
#Create Butter_Prices DataFrames
butter_prices=pd.DataFrame(prices.reshape(1,3), #reshape it its (3,) we have reshape it to (1,3)
                           index=["Price"], 
                           columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

In [ ]:
weekly_sales

In [ ]:
butter_prices.shape, weekly_sales.shape

In [ ]:
weekly_sales.T.shape

In [ ]:
daily_sales=butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales

In [ ]:
weekly_sales["Total ($)"]=daily_sales.T
weekly_sales

In [80]:
daily_sales

NameError: name 'daily_sales' is not defined

# Comparison Operators

In [71]:
a1=array1

In [72]:
a1

array([1, 2, 3])

In [73]:
a2

array([[1. , 2.5, 3.3],
       [4. , 5.6, 6.6]])

In [74]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [75]:
a1>=a2

array([[ True, False, False],
       [False, False, False]])

In [76]:
bool_arrays=a1>=a2

In [77]:
type(bool_arrays)

numpy.ndarray

In [78]:
bool_arrays.dtype

dtype('bool')

In [79]:
a1==a2

array([[ True, False, False],
       [False, False, False]])

# Sorting Arrays

In [83]:
random_array, random_array.shape

(array([[4, 7, 2, 9, 6],
        [7, 3, 6, 8, 1],
        [8, 2, 4, 7, 8]]),
 (3, 5))

In [84]:
np.sort(random_array)

array([[2, 4, 6, 7, 9],
       [1, 3, 6, 7, 8],
       [2, 4, 7, 8, 8]])

In [85]:
np.argsort(random_array)

array([[2, 0, 4, 1, 3],
       [4, 1, 2, 0, 3],
       [1, 2, 3, 0, 4]])

In [86]:
np.argmax(random_array)

3

In [87]:
np.argmin(random_array)

9

# Practical Numpy in Actions

<img src="images/panda.png">

In [89]:
#Turn image into Numpy
from matplotlib.image import imread
panda=imread("images/panda.png")

In [90]:
panda.dtype

dtype('float32')

In [91]:
type(panda)

numpy.ndarray

In [93]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [94]:
 panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png">

In [96]:
car=imread("images/car-photo.png")

In [101]:
car[:2], car.shape, car.ndim, type(car), car.size

(array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
         [0.3372549 , 0.34509805, 0.30588236, 1.        ],
         [0.20392157, 0.21568628, 0.14901961, 1.        ],
         ...,
         [0.64705884, 0.7058824 , 0.54901963, 1.        ],
         [0.59607846, 0.63529414, 0.45882353, 1.        ],
         [0.44705883, 0.47058824, 0.3372549 , 1.        ]],
 
        [[0.44313726, 0.43529412, 0.40392157, 1.        ],
         [0.3137255 , 0.31764707, 0.27450982, 1.        ],
         [0.2       , 0.21176471, 0.14117648, 1.        ],
         ...,
         [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
         [0.49803922, 0.52156866, 0.39607844, 1.        ],
         [0.4       , 0.42745098, 0.34117648, 1.        ]]], dtype=float32),
 (431, 575, 4),
 3,
 numpy.ndarray,
 991300)

<img src="images/dog-photo.png">

In [102]:
dog=imread("images/dog-photo.png")

In [104]:
dog[:1], dog.size, dog.ndim, type(dog)

(array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
         [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
         [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
         ...,
         [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
         [0.49411765, 0.68235296, 0.8392157 , 1.        ],
         [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32),
 993600,
 3,
 numpy.ndarray)